# Generated by Django 3.2.3 on 2021-07-23 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_record_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=50)),
                ('quest_target', models.IntegerField()),
                ('quest_target_type', models.CharField(choices=[('S', 'Score'), ('+', 'Addition'), ('-', 'Substraction'), ('*', 'Multiplication'), ('/', 'Division')], max_length=1)),
                ('quest_type', models.CharField(choices=[('A', 'Akumulatif'), ('B', '')], max_length=1)),
                ('current_progress', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
