# Generated by Django 3.2.3 on 2021-07-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailyquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='current_progress',
            field=models.IntegerField(default=0),
        ),
    ]
