# Generated by Django 3.2.3 on 2021-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
