# Generated by Django 3.2.3 on 2021-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp_needed',
            field=models.IntegerField(default=100),
        ),
    ]
