# Generated by Django 3.2.3 on 2021-07-31 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_quest',
            field=models.BooleanField(default=False),
        ),
    ]
