# Generated by Django 3.2.3 on 2021-07-31 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210731_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquest',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
